
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Size = {
  Small: 'Small',
  Medium: 'Medium',
  Large: 'Large'
} as const

export type Size = (typeof Size)[keyof typeof Size]


export const OrderStatus = {
  PAID: 'PAID',
  FAILED: 'FAILED'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]
